language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - build-tools-26.0.1
  - android-26
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - ".+"
script:
- "./gradlew clean assembleDebug"
notifications:
  email: false
sudo: false
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$ANDROID_HOME"