language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - build-tools-27.0.3
  - android-27
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - ".+"
# exclude ci builds for stable branch
branches:
  only:
  - o8x-exp

before_install:
  - "./notify.sh"
install:
  - yes | sdkmanager "ndk-bundle" "cmake;3.6.4111459" "lldb;3.0" --channel=3
script:
  - "./gradlew clean assembleDebug"
notifications:
  email: false
  slack:
    secure: brEfRELSx+x83DFQqSbOJQJy5NsRH3j+n3udfr2k3K9tugnnq7+u9h4sLfwlIvjHKqYJqqiN9/u13W1FNsWkNQFcBLoUBSEK9UDi3HdCWGTcYt6GvlilOid9TH6dn5fksJ6ya/3pYCu6Xal9McIN4gwL7oNL5NOEboiPD5tLU2zE1rifABknlY/6jA7brTaIOdNSHTYUIKfhRkob6v4V7QapVaw8KUU881QoDp3DkDhgStL4bWX4YefYs2MgmXWtzA9Vb8XMgGuvAKVKOwyk4h2SQPJMDVgjDzqeRCGsmnYUapUQNxMCAcXhjZ2+PfbdO8C0d9QuYF3YynBdYfSyr8fyuDkxnZ8aLJV/OOIkFP+Z0AH8MbUaF/jL1SyPWRBwESNHUvj0OtH8r0XO9HcQtnoiAIZdlOJrq8m17Z2JWMrNIQw6//WSMp4cvjZZW9CKnalbhYP5rItag3m+ROywOvLv97gQ6kEtZwVUkHiOF3/ytKQxkZZt6eXc6Q3wnqXLkEV49gBQb9qjzGbAGD4FdjljnYdQRI1zmuFEcc1l0q+RDhWeieHgVbi1VugNIgVHVLiXXxp9G81bHJkgjqq8oXfBjFcWxgysPoHWJIdRVv865PClhgnPAecqo+LAUYuSYjZweopCwdymBWFX+9KsA6tQz9ZVhJqTLeSBPmzwzuI=
sudo: false
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$ANDROID_HOME"
after_success:
  - "./push_pass.sh"
after_failure:
  - "./push_fail.sh"
