language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - build-tools-26.0.1
  - android-26
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - ".+"
before_install:
  - "./notify.sh"
script:
- "./gradlew clean assembleDebug"
notifications:
  email: false
  slack:
    secure: brEfRELSx+x83DFQqSbOJQJy5NsRH3j+n3udfr2k3K9tugnnq7+u9h4sLfwlIvjHKqYJqqiN9/u13W1FNsWkNQFcBLoUBSEK9UDi3HdCWGTcYt6GvlilOid9TH6dn5fksJ6ya/3pYCu6Xal9McIN4gwL7oNL5NOEboiPD5tLU2zE1rifABknlY/6jA7brTaIOdNSHTYUIKfhRkob6v4V7QapVaw8KUU881QoDp3DkDhgStL4bWX4YefYs2MgmXWtzA9Vb8XMgGuvAKVKOwyk4h2SQPJMDVgjDzqeRCGsmnYUapUQNxMCAcXhjZ2+PfbdO8C0d9QuYF3YynBdYfSyr8fyuDkxnZ8aLJV/OOIkFP+Z0AH8MbUaF/jL1SyPWRBwESNHUvj0OtH8r0XO9HcQtnoiAIZdlOJrq8m17Z2JWMrNIQw6//WSMp4cvjZZW9CKnalbhYP5rItag3m+ROywOvLv97gQ6kEtZwVUkHiOF3/ytKQxkZZt6eXc6Q3wnqXLkEV49gBQb9qjzGbAGD4FdjljnYdQRI1zmuFEcc1l0q+RDhWeieHgVbi1VugNIgVHVLiXXxp9G81bHJkgjqq8oXfBjFcWxgysPoHWJIdRVv865PClhgnPAecqo+LAUYuSYjZweopCwdymBWFX+9KsA6tQz9ZVhJqTLeSBPmzwzuI=
sudo: false
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$ANDROID_HOME"
env:
  global:
  - secure: "EVRlhwIf2ZlYzmaJ01ypS9/n9YcXQIFrXjR8gU5M27rBir2YZ+CGnnsdALaqOZCKLOAEmyuh7VuIgupYZgPFRVWUc4sHA911DNKso6kVeEOZDg4gG3jVtCSNDFvzFtf0Abq1pvQ8pvbrPzpz+eT2veb2HSMDdfz6PcxktQdoEp1uz8k+0vPCccpag6dZlVg9UfPeNf8OLWiL5Hu1vx2lY1NOMtNBDHdKI3IU2RUu85oCw4ADtz5C6nft4ZQ16PwD117oPbeX1oaM7G5gA89MzBvwDOqcqS50NRuf0Fyb/5kP9HOUtYkh5wT7QiS5trUEXEy3LZ16ffeq092klZOI1W2s0sDfTq1KGXJ3m7CiQgGnPxuTc8/1CufogeKp8YzIIG4RYoANlpEBgg4L4i6LsOpKb1KtabCKo0H7KG41TvZhksnE4dwvCqk+ZPqlACnuvbtBgWyWNLsnRZzDYJiOaA6gvDPxBjbOnng0isUJ+ISpePFgy+nMmU1U7WSpqCfr6AqQBwC5xOtx1Xlh3XB0YT3JF3FUMYce9pYtV6Lpeezf+jS2fIocDARtTBvquECMMRYe5Kh8b8CTOb+GbVvpDPvHfATRHyLm4RvJ4nrWBKxSmJ8KiUTAeG3aHUeg70YhoNI/2o5B1dmXZ0x6Q+2mswDEQX5CwJ9SEjnyw00E784="
  - secure: "efT3PQy848Zt1xCMuESRw3oVSIvuEuYOjeFMIvUg0VmT9uHGS/SYBuXyC90U1voOEVXF/dsWsQg4zz1PLzDXdCTiYEAmuz2H6ChRgB5pYz6W203LKNUL459UlLiNVO/dEb4Xp3vCRH0a4T3Yu1FF9TzvOyY9cR/3bW91rNQZkpe50vKFTZURXbNdXWpDnJILDU1D+8V/mBdzTU8/Shnt8y6KBO2Qmn7IyDqKTDx4THsaMS8DehndGsPR5P16ztlqw7T0Ntg6ffn1KvP/k5LoO9WAf0tiagwUSw/Rj2MFD6znTPKDAW+BkaPSLE9p8V4S/y1NqmY9t+IJvJpv/kjMgoNj8YJ+2+5+5GU5zrw+jPEmRlHV/iNLgiZFX87F0P8eNnYDr5se6J/aHa3Gu0ocGJFzQBc5o7a27ukli1jq3MO+Yr0nLEmNDfS36CTaif2JeE+fNnaitGBds1HubpUHyV2GWjadkYK58yrw8yOHmze5sB2ZPYvowXkTqAF8C650o/xzhCQxleY6/Jll/Y91mfidPaJlntC7D8NF8iayQLwUmepa74s3ROEQgp19VTavcXAOpMq2gPtyNFV4X+y1+QQmYeydbb+hY2re844amfUch5vDEG+O0z/2cNYLNF0fV7iGidB0DnjEqsZDTgTcEyF/OzhtoJBAbcg3CBXrhIM="
  - secure: "XhNfjzlqL/v48jAkGRx8QIGp4XCLq/Nar48TkNfoBNNrflbgGfkNXCGk93d2FisvHq8XIAgz+4xlhjentJyahgojwysjcjjef+bzqBehuoH9tZFnobz6Wdk2aKK9TQ30LWGz7IL/IJVvahwEO1BbHYut6/H63ei3vAHeo/vDJj5rf8KOIKOU6TEakZEoWYV6MPj9gyscvlc5SCCaIgkXRrKH7qsY+oMUhPCeUq9lEJ8P1B7pwM39J1kFtMEQk8jTpIaZN5/qhqlbDJHpFs8Hj/MfbUN1LeKJZyEM0nOPMomatIY+nm78DZb+NpPoCGtfW4GyJDH/5FqlQGcBbb8uXx+r2ORSyDUYpHHuOIdf55EzxqtIYOrUbYrCQoEAiuW9uqxXddtBuRPcYActnVPcrjoiHxe1052/716aFN0DhckYe3/RuXBTLlfkX9Tdr3JqOK5FH2XHi+w4t5sXKY0N3vnnsVAQDBdxz2FUbF/gCX1Gk9ihDf4oEuR0HsUWQO6LaAC0McPwXL+N/sJ/KBJ6P5GW+swYwaK8P+m9qsmYSWsSAnHfWFZlVXKPNDrY0QVV6LfnSb3bbHT/Hp8Ut6maoBet5cfXZlrdISa6S+yeUFNECM04ibIRJyMR7Hq6iRIT4fLs+JqBrzcxDnLuNNJpdm25Nb0XDm0EQUBQh77CDFM="
after_success:
  - "./push.sh"

